### ISSUE TITLE
I cant start a new campaign.

### ISSUE THREAD

**Issue by TheHawk3r** [ReaperAnon/Middle-Earth-Mod-Loader#1]
when i try to start a new campaign the game crashes

**Comment by ReaperAnon** [comment]
It's the same issue as the option changing one, can't do anything about
that. Just follow the instructions.

**Comment by RpgPlayer156** [comment]
Hi,

I've followed the installation instructions, but the game wont launch as it's missing the bink2w64.dll once it's renamed. So I launched it without renaming it, then alt-abbed and renamed it but the mod loader wont appear with F10.

Is this the same issue as above? Or does this mod not work wit tthe latest version of the game?. 
Thanks.

**Comment by ReaperAnon** [comment]
How did you manage to follow the installation instructions without
installing the mod?

**Comment by RpgPlayer156** [comment]
I did this as per the readme:
- Installed Microsoft redistributables
- Renamed bink2w64.dll to bink2w64_.dll
- Unzipped contents of archive mod loader archive into '...\steamapps\common\ShadowOfWar\x64' folder
- Created 'plugin' folder in the same location
- Dropped alll of the mod folders fo SOW into the plugin folder

And then I get a message on starting the game that the bink2w64.dll file is missing.

Thanks.

**Comment by ReaperAnon** [comment]
Well the archive has bink2w64.dll in it. It can't be missing if you did
what you said.

**Comment by RpgPlayer156** [comment]
Ok, so I looked in the contents of the 'output' folder and transferred the 3 bink2w64.dll, bink2w64.exp & bink2w64.lib files in there into the ...x64 folder and now the mod loader loads. Renamed the original bink2w64_.dll file as well. But there's nothing loading under the plugins page.

So instead of dropping the folder as per the readme instructions, or all the seperate folders and loose files, I tried loading the contents of the folders themselves and the mods now appear.

I'm only interested in the multi equip skills mod. But when I press L-ctrl it doesn't highlight 2 upgrades. I get the sound, but no highlighted upgrade.

Can I ask please what files from which folders I need to put in the plugins folder for this mod to work?. I'm just guessing at this point and loaded: CheatHotkeys, Output, Shared dependencies, the loose files, and overwrote them all with the multi skills equip files.

Thanks.
